name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 14.16.1
      uses: actions/setup-node@main
      with:
        node-version: 14.16.1
    - name: Checkout
      uses: actions/checkout@main    
    - name: deploy
      uses: iShambhuJha/covid-tracker-india@main
     
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: gh-pages
        BASE_HREF: https://iShambhuJha.github.io/covid-tracker-india/
        FOLDER: dist/covid-tracker-india
        BUILD_SCRIPT: npm install && npm run build -- --prod
